name: Derek Kniffin
#url: http://www.kniffin.us/derek
url: http://wheatley.int.colorado.edu/personal-website
# url: http://localhost:4000/

markdown: redcarpet
highlighter: pygments
exclude: [notes]

# Glynn configs (deployment)
# to deploy, simply run `glynn` on the cmd line
ftp_host: 'kniffin.us'
ftp_dir: '/public_html/derek'
ftp_passive: false

# optional
ftp_port: 21
ftp_username: 'derek@kniffin.us'
